name: Update README with Latest Commit

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the 'main' branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest commit details
        run: |
          # Fetch the latest commit hash and commit message
          COMMIT_HASH=$(git log -1 --format=%H)
          COMMIT_MESSAGE=$(git log -1 --format=%s)
          
          # Get the repository name (for this case it's Ahsanjuly29)
          REPO_NAME="Ahsanjuly29"

          # Append commit info to the README file
          echo "" >> README.md  # Add a new line for better formatting
          echo "## Latest Commit" >> README.md
          echo "" >> README.md
          echo "### Latest Commit Details" >> README.md
          echo "" >> README.md
          echo "- **Commit Message:** $COMMIT_MESSAGE" >> README.md
          echo "- **Repository:** [${REPO_NAME}](https://github.com/Ahsanjuly29/$REPO_NAME)" >> README.md
          echo "- **Commit URL:** [https://github.com/Ahsanjuly29/$REPO_NAME/commit/$COMMIT_HASH](https://github.com/Ahsanjuly29/$REPO_NAME/commit/$COMMIT_HASH)" >> README.md

      - name: Commit changes to README
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Ahsanjuly29
          author_email: ahsan.july29@gmail.com  # Ensure this is your actual email
          message: "Update README with latest commit details"
